version: '3'

services:
  apigateway:
    build: ./apigateway
    ports:
      - "1887:1887"
    volumes:
      - ./apigateway:/usr/src/app
    environment:
      AMQP_URL: rabbitmq
      ROUTING_SERVICE: gateway-listener
  connservice:
    build: ./connservice
    volumes:
      - ./connservice:/usr/src/app
    environment:
      AMQP_URL: rabbitmq
      ROUTING_SERVICE: gateway-listener
      VERIFICATION_SERVICE: auth-listener
      OAUTH_URI_SERVICE: auth-service
      SUBSCRIPTION_SERVICE: subscription-service
      PUBLISH_SERVICE: publish-service
      SESSION_SERVICE: session-service
      MESSAGE_SERVICE: message-service
      DB_NAME: mydb
      DB_USER: root
      DB_PASS: root
      DB_HOST: conn_db
  authentication:
    build: ./authentication
    ports:
      - "55000:5000"
    volumes:
      - ./authentication:/usr/src/app
    environment:
      AMQP_URL: rabbitmq
      OAUTH_URI_SERVICE: auth-service
      VERIFICATION_SERVICE: auth-listener
      REDIRECT_URI: "https://127.0.0.1:55000/"
  sessionservice:
    build: ./sessionservice
    volumes:
      - ./sessionservice:/usr/src/app
    environment:
      AMQP_URL: rabbitmq
      SESSION_SERVICE: session-service
      SUBSCRIPTION_SERVICE: subscription-service
      PUBLISH_SERVICE: publish-service
      MESSAGE_SERVICE: message-service
      DB_NAME: mydb
      DB_USER: root
      DB_PASS: root
      DB_HOST: conn_db
  messages:
    build: ./messages
    volumes:
      - ./messages:/usr/src/app
    environment:
      AMQP_URL: rabbitmq
      MESSAGE_SERVICE: message-service
      ROUTING_SERVICE: routing-service
      DB_NAME: mydb
      DB_USER: root
      DB_PASS: root
      DB_HOST: conn_db
  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - "5672:5672"
  conn_db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - conn-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
  session_db:
    image: postgres:10-alpine
    volumes:
      - session-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb

volumes:
  conn-db-data:
  session-db-data:

